version: "3"
services:
  database:
    image: postgres:17
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  jar:
    image:
      imuftiev/date-bot-jar:latest
    depends_on:
      - database
    env_file:
      - .env
